name: corona_sd_plots
channels:
  - conda-forge
  - bioconda
dependencies:
  - biopython
  - blast
  - boost=1.68.0
  - boost-cpp=1.68.0
  - ete2
  - fasttree
  - gsl
  # - gst-plugins-base
  - hmmer
  - lxml
  - mafft
  - muscle
  - numpy
  - perl
  - pip
  - python=2.7
  - python_abi
  - r=3.6.0
  - r-ggplot2
  - r-gtable
  - r-magrittr
  - r-rcolorbrewer
  - r-recommended
  - r-tibble
  - r-ape
  - r-jsonlite
  - readline
  - setuptools
  - trimal=1.4.1
  - cd-hit
  - pip:
    - distance
